<a href="https://colab.research.google.com/github/nimrashaheen001/Programming_for_AI/blob/main/lab_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Quiz-2**

Perform following tasks on the provided Reviews Dataset.
* Drop words if not alphabets.
* Tokenize the sentence.
* Perform lemitization.
* Vectorize using bigram and trigram techniques.
* Apply Random Forest algorithm with 150 trees.
* Evaluate overall accuracy of the model and class-wise precision .

# **Drop words if not alphabets.**

In [ ]:
import numpy as np
import pandas as pd
temp_df = pd.read_csv('/content/reviews_dataset.csv')


import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

#exclude = "!.,?"
def remove_punc(text):
    return text.translate(str.maketrans('', '', exclude))
df['news'] = df['news'].str.lower()

df['news'] = df['news'].apply(remove_html_tags)

df['news'] = df['news'].apply(remove_url)

In [ ]:
df.head()

news      type
0  ['china', 'had', 'role', 'in', 'yukos', 'split...  business
1  ['oil', 'rebound', 'from', 'weather', 'effect'...  business
2  ['indonesia', "'declines", 'debt', 'freeze', "...  business
3  ['$', '1m', 'payoff', 'for', 'former', 'shell'...  business
4  ['us', 'bank', 'in', '$', '515m', 'sec', 'sett...  business

In [ ]:
df['news'][1]

'[\'oil\', \'rebound\', \'from\', \'weather\', \'effect\', \'oil\', \'price\', \'recovered\', \'in\', \'asian\', \'trade\', \'on\', \'tuesday\', \',\', \'after\', \'falling\', \'in\', \'new\', \'york\', \'on\', \'milder\', \'winter\', \'weather\', \'across\', \'the\', \'us\', \'.\', \'with\', \'winter\', \'temperature\', \'staying\', \'relatively\', \'high\', \'in\', \'the\', \'northern\', \'us\', \',\', \'a\', \'barrel\', \'of\', \'light\', \'crude\', \'ended\', \'monday\', \'down\', \'$\', \'1.33\', \'to\', \'$\', \'42.12\', \'.\', \'however\', \'crude\', \'price\', \'have\', \'rebounded\', \'in\', \'asia\', \',\', \'rising\', \'to\', \'$\', \'42.30\', \'a\', \'barrel\', \'for\', \'february\', \'delivery\', \'.\', \'in\', \'london\', \',\', \'trading\', \'of\', \'brent\', \'crude\', \'wa\', \'suspended\', \'for\', \'a\', \'public\', \'holiday\', \',\', \'but\', \'the\', \'price\', \'fell\', \'to\', \'$\', \'39.20\', \'in\', \'the\', \'far\', \'east\', \'.\', \'with\', \'milder\', \'t

news      type
0  China had role in Yukos split-up\n \n China le...  business
1  Oil rebounds from weather effect\n \n Oil pric...  business
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business
3  $1m payoff for former Shell boss\n \n Shell is...  business
4  US bank in $515m SEC settlement\n \n Five Bank...  business

## **Tokenize the sentence.**

In [ ]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize,sent_tokenize
sent1 = 'I am going to visit delhi!'
word_tokenize(sent1)
#df['sentences'] = df['review'].apply(sent_tokenize)
df['news'] = df['news'].apply(word_tokenize)
df['news'][1]

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


['Oil',
 'rebounds',
 'from',
 'weather',
 'effect',
 'Oil',
 'prices',
 'recovered',
 'in',
 'Asian',
 'trade',
 'on',
 'Tuesday',
 ',',
 'after',
 'falling',
 'in',
 'New',
 'York',
 'on',
 'milder',
 'winter',
 'weather',
 'across',
 'the',
 'US',
 '.',
 'With',
 'winter',
 'temperatures',
 'staying',
 'relatively',
 'high',
 'in',
 'the',
 'northern',
 'US',
 ',',
 'a',
 'barrel',
 'of',
 'light',
 'crude',
 'ended',
 'Monday',
 'down',
 '$',
 '1.33',
 'to',
 '$',
 '42.12',
 '.',
 'However',
 'crude',
 'prices',
 'have',
 'rebounded',
 'in',
 'Asia',
 ',',
 'rising',
 'to',
 '$',
 '42.30',
 'a',
 'barrel',
 'for',
 'February',
 'delivery',
 '.',
 'In',
 'London',
 ',',
 'trading',
 'of',
 'Brent',
 'crude',
 'was',
 'suspended',
 'for',
 'a',
 'public',
 'holiday',
 ',',
 'but',
 'the',
 'price',
 'fell',
 'to',
 '$',
 '39.20',
 'in',
 'the',
 'Far',
 'East',
 '.',
 'With',
 'milder',
 'temperatures',
 'expected',
 'to',
 'continue',
 'in',
 'the',
 'northern',
 'parts',
 'of',
 't

# **Perform lemitization.**

In [ ]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmitizer = WordNetLemmatizer()
# Function to lemmatize words
def lemmatize_words(text):
    lemmatizer = WordNetLemmatizer()
    return [lemmatizer.lemmatize(word) for word in text]
df['news'] = df['news'].apply(lemmatize_words)
df['news'][1]

[nltk_data] Downloading package wordnet to /root/nltk_data...


['Oil',
 'rebound',
 'from',
 'weather',
 'effect',
 'Oil',
 'price',
 'recovered',
 'in',
 'Asian',
 'trade',
 'on',
 'Tuesday',
 ',',
 'after',
 'falling',
 'in',
 'New',
 'York',
 'on',
 'milder',
 'winter',
 'weather',
 'across',
 'the',
 'US',
 '.',
 'With',
 'winter',
 'temperature',
 'staying',
 'relatively',
 'high',
 'in',
 'the',
 'northern',
 'US',
 ',',
 'a',
 'barrel',
 'of',
 'light',
 'crude',
 'ended',
 'Monday',
 'down',
 '$',
 '1.33',
 'to',
 '$',
 '42.12',
 '.',
 'However',
 'crude',
 'price',
 'have',
 'rebounded',
 'in',
 'Asia',
 ',',
 'rising',
 'to',
 '$',
 '42.30',
 'a',
 'barrel',
 'for',
 'February',
 'delivery',
 '.',
 'In',
 'London',
 ',',
 'trading',
 'of',
 'Brent',
 'crude',
 'wa',
 'suspended',
 'for',
 'a',
 'public',
 'holiday',
 ',',
 'but',
 'the',
 'price',
 'fell',
 'to',
 '$',
 '39.20',
 'in',
 'the',
 'Far',
 'East',
 '.',
 'With',
 'milder',
 'temperature',
 'expected',
 'to',
 'continue',
 'in',
 'the',
 'northern',
 'part',
 'of',
 'the',
 '

# **Vectorize using bigram and trigram techniques.**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

X = df['news']
Y = df['type']

print(X)
print(Y)

encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

print(Y)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42) # You can adjust test_size and random_state

# Apply CountVectorizer to the training data
cv = CountVectorizer(ngram_range=(2,2))

X_train_n_gram = cv.fit_transform(X_train.astype(str))
X_test_n_gram = cv.transform(X_test.astype(str))

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_n_gram.shape}")
print(f"Shape of X_test_bow: {X_test_n_gram.shape}")

rf = RandomForestClassifier()

rf.fit(X_train_n_gram,y_train)
y_pred = rf.predict(X_test_n_gram)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

cv = CountVectorizer(ngram_range=(3,3)) # Change to (3,3) for trigrams

X_train_n_gram = cv.fit_transform(X_train.astype(str))
X_test_n_gram = cv.transform(X_test.astype(str))

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_n_gram.shape}")
print(f"Shape of X_test_bow: {X_test_n_gram.shape}")

rf = RandomForestClassifier()

rf.fit(X_train_n_gram,y_train)
y_pred = rf.predict(X_test_n_gram)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

0       ['china', 'had', 'role', 'in', 'yukos', 'split...
1       ['oil', 'rebound', 'from', 'weather', 'effect'...
2       ['indonesia', "'declines", 'debt', 'freeze', "...
3       ['$', '1m', 'payoff', 'for', 'former', 'shell'...
4       ['us', 'bank', 'in', '$', '515m', 'sec', 'sett...
                              ...                        
2220    ['microsoft', 'launch', 'it', 'own', 'search',...
2221    ['warnings', 'about', 'junk', 'mail', 'deluge'...
2222    ['microsoft', 'get', 'the', 'blogging', 'bug',...
2223    ['gamers', 'snap', 'up', 'new', 'sony', 'psp',...
2224    ['apple', 'laptop', 'is', "'greatest", 'gadget...
Name: news, Length: 2225, dtype: object
0       business
1       business
2       business
3       business
4       business
          ...   
2220        tech
2221        tech
2222        tech
2223        tech
2224        tech
Name: type, Length: 2225, dtype: object
[0 0 0 ... 4 4 4]
Shape of X_train_bow: (1780, 271258)
Shape of X_test_bow: (445, 271258)
0.858

# **Apply Random Forest algorithm with 150 trees.**


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix


# Apply TF-IDF vectorization
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train.astype(str))
X_test_tfidf = tfidf.transform(X_test.astype(str))

print(f"Shape of X_train_tfidf: {X_train_tfidf.shape}")
print(f"Shape of X_test_tfidf: {X_test_tfidf.shape}")

# Apply Random Forest with 150 trees
rf = RandomForestClassifier(n_estimators=150)  # Specify 150 trees
rf.fit(X_train_tfidf, y_train)
y_pred = rf.predict(X_test_tfidf)

# Evaluate the model
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Shape of X_train_tfidf: (1780, 25028)
Shape of X_test_tfidf: (445, 25028)
0.950561797752809
[[108   0   3   2   2]
 [  2  67   2   0   1]
 [  2   0  74   0   0]
 [  0   0   0 102   0]
 [  5   1   0   2  72]]


# **Evaluate overall accuracy of the model and class-wise precision**

In [ ]:
from sklearn.metrics import accuracy_score


overall_accuracy = accuracy_score(y_test, y_pred)
print(f"Overall Accuracy: {overall_accuracy}")
from sklearn.metrics import confusion_matrix, precision_score


cm = confusion_matrix(y_test, y_pred)


num_classes = cm.shape[0]


for i in range(num_classes):
    tp = cm[i, i]  # True positives for class i
    fp = sum(cm[:, i]) - tp  # False positives for class i
    precision = tp / (tp + fp) if (tp + fp) != 0 else 0  # Handle zero division
    print(f"Precision for class {i}: {precision}")


Overall Accuracy: 0.950561797752809
Precision for class 0: 0.9230769230769231
Precision for class 1: 0.9852941176470589
Precision for class 2: 0.9367088607594937
Precision for class 3: 0.9622641509433962
Precision for class 4: 0.96
